services:
  mysql:
    image: mysql:8.0
    container_name: snibby-mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/snibby.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=snibby
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_ROOT_PASSWORD=admin

  redis:
    image: redis:7.2.5
    container_name: snibby-redis
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:6.0.16
    container_name: snibby-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=local
      - MONGO_INITDB_DATABASE=snibby
